-- MySQL Script generated by MySQL Workbench
-- Wed Apr  3 14:48:51 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`membre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`membre` (
  `id` INT NULL,
  `prenom` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `photo` VARCHAR(45) NULL,
  `coach_nom` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`spectacle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`spectacle` (
  `nom` VARCHAR(35) NULL,
  `date` DATE NULL,
  `heure` DATETIME NULL,
  `spectaclecol` VARCHAR(45) NULL,
  `idSpectacle` INT NULL,
  `spectaclecol1` VARCHAR(45) NULL,
  PRIMARY KEY (`idSpectacle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categorie` (
  `id` INT NULL,
  `heure` DATETIME NULL,
  `spectacle_nom` VARCHAR(35) NULL,
  `spectacle_date` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_categorie_spectacle1_idx` (`spectacle_nom` ASC, `spectacle_date` ASC) VISIBLE,
  CONSTRAINT `fk_categorie_spectacle1`
    FOREIGN KEY (`spectacle_nom` , `spectacle_date`)
    REFERENCES `mydb`.`spectacle` (`nom` , `date`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`atelier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`atelier` (
  `idnom` INT NULL,
  `date` DATE NULL,
  `membre_nom` VARCHAR(30) NULL,
  `membre_prenom` VARCHAR(45) NULL,
  `membre_email` VARCHAR(45) NULL,
  `membre_photo` VARCHAR(45) NULL,
  PRIMARY KEY (`idnom`),
  INDEX `fk_atelier_membre1_idx` (`membre_nom` ASC, `membre_prenom` ASC, `membre_email` ASC, `membre_photo` ASC) VISIBLE,
  CONSTRAINT `fk_atelier_membre1`
    FOREIGN KEY (`membre_nom` , `membre_prenom` , `membre_email` , `membre_photo`)
    REFERENCES `mydb`.`membre` (`id` , `prenom` , `email` , `photo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comedien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comedien` (
  `id` INT NULL,
  `membre_coach_nom` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comedien_membre1_idx` (`membre_coach_nom` ASC) VISIBLE,
  CONSTRAINT `fk_comedien_membre1`
    FOREIGN KEY (`membre_coach_nom`)
    REFERENCES `mydb`.`membre` (`coach_nom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`coach`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`coach` (
  `_id` INT NULL,
  `membre_coach_nom` VARCHAR(30) NULL,
  PRIMARY KEY (`_id`),
  CONSTRAINT `fk_coach_membre1`
    FOREIGN KEY (`_id` , `membre_coach_nom`)
    REFERENCES `mydb`.`membre` (`id` , `coach_nom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
